default_stages: [commit]
repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: meta
    hooks:
      - id: check-hooks-apply
        name: check hooks apply to the repository
      - id: check-useless-excludes
        name: check for useless excludes

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: ["--style=Google", "--sort-includes"]
      - id: clang-tidy
      - id: oclint
      - id: uncrustify
      - id: cppcheck
      - id: cpplint
      - id: include-what-you-use

  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        description: Shell source code linter (https://www.shellcheck.net/)
        entry: shellcheck
        language: system
        types: [shell]
        stages: [commit]
      - id: shfmt
        name: shfmt
        description: Shell source code formatter (https://github.com/mvdan/sh)
        entry: shfmt
        language: system
        types: [shell]
        stages: [commit]
