load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "add-binary",
    srcs = ["add-binary.cpp"],
)


cc_binary(
    name = "add-two-numbers",
    srcs = ["add-two-numbers.cpp"],
)

cc_binary(
    name = "construct-k-palindrome-strings",
    srcs = ["construct-k-palindrome-strings.cpp"],
)

cc_binary(
    name = "image-overlap",
    srcs = ["image-overlap.cpp"],
)

cc_binary(
    name = "two-sum",
    srcs = ["two-sum.cpp"],
)
